### ISSUE TITLE
[EPIC]: Keeper System for Synthetix

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/issues#10]
### Summary
Implement the keeper system for Synthetix Protocol, involves writing keeper contracts and the keeper ecosystem (either chainlinks keeper system or any other solution)

### Docs, specs.
Notes - https://docs.google.com/document/d/1tQ6sqIga9yKHnbBYYY3O5Fnt-IncOzKdn3zi6dvZWK0/edit#

Synthetix Keeper functions spreadsheet - https://docs.google.com/spreadsheets/d/1iBur1ku8eOLJL3_h3AnvDu4Efahjm7Wu5vNeoRdwngQ/edit#gid=0

https://docs.google.com/document/d/1btVxjEU0rhe2ZoUdLmeDUvezftD4Wkdb0VwFnuna3Is/edit#

Exploration - https://github.com/Synthetixio/synthetix/tree/snx-keepers/keeper-exploration

### Tasks
- [ ] Go through the spreadsheet of the functions that need to be kept and write the contracts for them
- [ ] Figure out which system the Synthetix network wants to use to KEEP

### QA Tasks
- [ ] Add first QA step here

**Comment by andytcf** [comment]
[Chainlink]: K33P3R system is still in beta
