### ISSUE TITLE
[EPIC] Futures Contracts: Stretch Tasks

### ISSUE THREAD

**Issue by zyzek** [Synthetixio/issues#102]
As required, select some of these and turn them into their own cards for implementation.

- [ ] Convert FuturesMarketSettings into a mixin like MixinSystemSettings
- [ ] In-house funding rate arbitrage bot with zero-fee whitelist.
- [ ] Batched order confirmation / liquidation for keeper efficiency and responsiveness
- [ ] Now that there are fees on L2, migrate to confirmation incentives paid out of margin (or use the Gas Tank).
- [ ] Historical price / restrospective liquidations
- [ ] Fill orders with prices of the roundId immediately after they submitted rather than the current price, in case confirmation keepers fail to fill the order in time.
- [ ] Allow data contract to report overall market leverage and leverage per-side
- [ ] Allow data contract to report a user's overall leverage across all markets.
- [ ] Consider tokenising futures positions so they can be transferred between users
- [ ] Limit orders
- [ ] Proper debt cache integration with deltas and separate debt components per market, a la synths. Keeper would need to be updated to support partial updates from markets. (probably redundant if the computation gets centralised)

**Comment by zyzek** [comment]
Migrated these elements back into the Epic (#106).
