### ISSUE TITLE
Add the transfer functionality to Staking dApp

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/issues#11]
### Summary
Before we deprecate Mintr dApp we need to make sure that Staking dApp has all the essential features that users rely on Mintr for starting with the ```transfer```work flow.

The UI must call ```transfer and settle``` instead of just transfer, because metamask does not allow this natively. 

### Tasks
- [x] Design the transfer functionality that exist on Mintr
- [x] Design a banner ```please make sure the url is staking.sythetix.io, bookmark this page to be safe```, dismissing should store the state into local storage
- [x] Implement the transfer functionality on Staking
- [x] Implement the banner on layout

### QA Tasks
- [ ] A user should be able to transfer ETH to another wallet within the dApp
- [x] A user should be able to transfer SNX/sUSD to another wallet within the dApp
- [x] Transferring sUSD should call transfer and settle

**Comment by zoe-archer** [comment]
Designs for Transfer function + banner under Wallet > Synths
https://www.figma.com/file/M58E2cxkOgTPWMHRX7FTna/Staking-User-Flows?node-id=3376%3A0

**Comment by andytcf** [comment]
https://github.com/Synthetixio/staking/pull/512

**Comment by drptbl** [comment]
Transferring ETH is not done yet.
