### ISSUE TITLE
[EPIC] Staking dapp responsive design: phase 2

### ISSUE THREAD

**Issue by kelonye** [Synthetixio/issues#126]
Dev tasks
- [x] Make mobile sidenav toggleable via swipe
- [x] Indicate secondary path in header title
- [ ] Staked and debt value modals on [home page](https://www.figma.com/file/maCDRPNi3ewRnhHGe2togk/Staking-Mobile?node-id=135%3A75051)
- [x] Refine tiles layout on home screen
- [x] Refine tiles layout on mint/burn screens
- [x] More tables refinements

**Comment by kelonye** [comment]
Moved staked and debt values ticket into its own ticket
