### ISSUE TITLE
[EPIC] Include proper quotes and offer any token to sUSD functionality on 1inch on-ramp

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/issues#13]
### Summary
Currently, the 1inch on-ramp is disabled as it was showing inaccurate price quotes and causing users to unknowingly lose funds to slippage. 

To fix this, the 1inch on-ramp should be usable without leaving Kwenta and must include accurate quotes, showing the associated slippage with trades via 1inch as necessary.

1inch also offers any cryptocurrency to sUSD, we should include this functionality in the update.

_notes:_
See: https://www.npmjs.com/package/@0xsequence/multicall

### Tasks
- [x] Do a full revamp of 1inch integration + all the slippage information 
- [x] Add support for any ERC20 token (not just ETH-sUSD)
- [x] Fix critical issues (https://github.com/Synthetixio/kwenta/issues?q=is%3Aissue+is%3Aopen+label%3Aconvert)

### QA Tasks
- [x] ETH to sUSD (no approval needed)
- [x] ERC-20 to sUSD (approval needed)
- [x] Check sUSD estimates.. they should be more or less correct (what is shown vs what you actually get)
- [x] Check the slippage loss (like, how much you "lose" on the trade")
- [x] Check if other functionalities on kwenta work without issues
- [x] Retest slippage
- [x] Regression testing for fixed issues

**Comment by drptbl** [comment]
I've finished my testing for now, will come back to it after critical issues are fixed.
https://github.com/Synthetixio/kwenta/issues?q=is%3Aissue+is%3Aopen+label%3Aconvert
