### ISSUE TITLE
[EPIC] Change L2 mainnet owner to a multisig

### ISSUE THREAD

**Issue by eternauta1337** [Synthetixio/issues#132]
## Summary
We'd like to change the L2 ownership to ScopeLift's L2 multisig, which is a port of the legacy gnosis multisig.

## Notes
* Official dapp: https://ogg.scopelift.co/
* Commit history analysis: https://app.diagrams.net/#G1JXWJ_VHAdySWCKfK3pxwxBEeQpZ1yc0m
* Verification util: https://github.com/ajsantander/ovm-og-multisigwallet/blob/master/scripts/verify-bytecode.js (`npm run script verify-bytecode --network kovan --contract-address 0x192fB906627f2158283Ce79C15F72bc231C4CeD6`)

## Tasks
- [ ] Finish the changes to the scripts @i-stam 
- [ ] _WIP_ Study the commit and forking history of the code and their diffs @ajsantander 
- [ ] _WIP_ Verify the bytecode of an instance @ajsantander 
- [x] Decide and prepare owners - 3 of 4 and one is the deployer, us for now
- [ ] Build multi-sig @ajsantander 
- [ ] Prepare a runsheet @ajsantander 
- [ ] Test migrating the owner in kovan-ovm @ajsantander and @i-stam 
- [ ] Run the ownership migration @justinjmoses @i-stam @ajsantander
