### ISSUE TITLE
[TASK]: Investigate DNS caching issues (kwenta/staking dapp)

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/issues#146]
### Summary
It was temporary fixed with invalidating a cache (https://github.com/Synthetixio/kwenta/pull/356/files) on release, however release process shouldn't really need cache invalidation - it should work out of the box. The main task of this issue is to investigate DNS caching issue on CloudFront and make it work without invalidating a cache which shouldn't be necessary.

This issue occurs only on staking dapp, while it has the same setup as for example kwenta where this issue doesn't occur. It started happening after releasing a staking dapp with new wallet connector; infra settings haven't been touched.

### Tasks
- [x] Investigate DNS caching issue and find a root cause
- [x] Fix the issue (has to be fixed by Vercel)
- [x] Remove DNS caching invalidation from release process

### QA Tasks
- [x] Verify that DNS caching issue doesn't exist anymore between different releases

**Comment by drptbl** [comment]
Even after disabling a CloudFront, some people are still reporting issues related to caching.

**Comment by drptbl** [comment]
Waiting for support reply.
Ticket #00031891

**Comment by drptbl** [comment]
<img width="798" alt="Screenshot 2021-07-13 at 01 27 18" src="https://user-images.githubusercontent.com/8177587/125367941-7b0e1300-e379-11eb-807d-51b9c04f0ce9.png">

**Comment by drptbl** [comment]
<img width="779" alt="Screenshot 2021-07-23 at 16 48 25" src="https://user-images.githubusercontent.com/8177587/126799638-c081b868-983d-4624-a3e7-93735531139e.png">

**Comment by kmeraz** [comment]
I just wanted to note here that it appears that we are seeing this issue on Kwenta as well. The frontend app makes requests to JS chunks but it receives 404's in response. Looks like the issue went away after 12 hours or so. Should we update the main body of the ticket to include that? @drptbl

**Comment by drptbl** [comment]
<img width="782" alt="Screenshot 2021-07-28 at 21 09 49" src="https://user-images.githubusercontent.com/8177587/127382178-6fb86839-efe2-46e1-91af-edbd94d481b1.png">

**Comment by drptbl** [comment]
Seems to be fixed now. Latest kwenta release worked fine. Closing.
