### ISSUE TITLE
[TASK]: Update dapps to support synth suspension

### ISSUE THREAD

**Issue by gberg1** [Synthetixio/issues#149]
### Tasks

- [x] Kwenta - PR 369
- [ ] Kwenta  another PR to ensure that "Market Closed" "Reset in Progress" applies to synths with SystemStatus.synthSuspended(bytes32)  - should show for sETC
- [ ] Synthetix synths page to be rebuilt with the latest synthetix module 
- [ ] Synthetix synths page to be connected to the releases pipeline to ensure new releases with synths rebuild the site
- [ ] Synthetix synths page to handle the SystemStatus.synthSuspended status to show that sETC is suspended
