### ISSUE TITLE
[EPIC]: Kwenta Landing Page Improvements

### ISSUE THREAD

**Issue by JChiaramonte7** [Synthetixio/issues#15]
### Summary
David G brought up some suggested about how the homepage could be improved. This ticket is for improving the clarity of information, adding CTA buttons, and other general fixes.

### Tasks
- [x] Move "powered by Synthetix" into header.
- [x] Change "zero liquidity" to "without slippage"
- [x] Add "Start Trading" call to action button to header
- [x] Add "Trade real world assets and derivatives on Ethereum"
- [x] Fix broken exchange
- [x] Make "Start Trading" header sticky

### QA
- [x] Note that header text is now "Derivatives trading with zero slippage"
- [x] Note that "Powered by Synthetix" is now under the header text.
- [x] Note that there is now a call to action "Start Trading" button in the middle of the hero section
- [x] Note the assets header text has been changed to "Trade real world assets and derivatives on Ethereum"
- [x] Note the broken exchange card/snippet has been fixed

**Comment by andytcf** [comment]
LGTM merging it in
