### ISSUE TITLE
Fix and refactor ovm prod tests

### ISSUE THREAD

**Issue by eternauta1337** [Synthetixio/issues#154]
### Summary

Optimism local production tests are currently disabled in CI because of instability in the new ops tool from Optimism. The tests can be run locally, but require manual docker sub-routine restarts. The goal is to make them stable again, and re-enable CI.

The current failure is that tests time out when waiting for the watcher to detect withdrawal finalizations.

Testing in this branch: `debugging-ovm-prod-tests`

### Tasks
- [x] **DONE** by @ajsantander Try spinning up the optimism environment, waiting a few minutes, and _then_ running the tests - deployed the instances, waited 10 minutes and triggered the tests. Also times out.
- [x] **DONE** by @ajsantander - Set a much larger timeout and see if they still fail locally - Left it running for a long time, doesn't seem to resume.
- [x] **DONE** by platocrat Reproduce bug and send logs to Optimism for studying
- [x] **DONE** by ajsantander - Try sending dummy transactions while waiting for the withdrawal to finalize
- [ ] ...
