### ISSUE TITLE
[TASK]: Candlesticks for Kwenta Charts

### ISSUE THREAD

**Issue by etn0m** [Synthetixio/issues#157]
### Summary
Improve the Kwenta trading experience by adding Candlesticks as an alternative to Line charts

Charting designs: https://www.figma.com/file/sghReDviy1lcr6kkNqlc0e/Kwenta-User-Flows?node-id=0%3A1

### Tasks
- [x] Investigate existing subgraph data
- [x] Investigate rechart support for candlesticks
- [x] Implement new subgraphs for candles
- [x] Display candlesticks
