### ISSUE TITLE
Complete Solidity code for SIP-112: EthWrappr  

### ISSUE THREAD

**Issue by liamzebedee** [Synthetixio/issues#16]
### Summary
Investigating/building a new contract which "Allow users to wrap ETH and get sETH".

SIP: [SIP-112](https://sips.synthetix.io/sips/sip-112).

Refs: [PR](https://github.com/Synthetixio/synthetix/pull/1178)

### Tasks
- [x] Feasibility investigation
- [x] Present to council for vote - ✅ passed https://staking.synthetix.io/gov/snxgov.eth/QmeMpeM9x4meydXWRBWgksuVk5yRvyL3gHkqYZfcrXPArA
- [x] Implementation
- [ ] Audited by IOSIRO
- [ ] Iterate

### QA Tasks
- [ ] Add first QA step here

**Comment by andytcf** [comment]
@liamzebedee closes this with the latest release
