### ISSUE TITLE
[TASK]: synthetix.io/synths overhaul

### ISSUE THREAD

**Issue by etn0m** [Synthetixio/issues#165]
### Summary
Synths page is outdated and needs to be hooked up to release pipeline and upgraded to read from our smart contracts for the latest status on synths.

### Todo
- [ ] Synthetix synths page to be rebuilt with the latest synthetix module 
- [ ] Synthetix synths page to be connected to the releases pipeline to ensure new releases with synths rebuild the site
- [ ] Synthetix synths page to handle the SystemStatus.synthSuspended status to show that sETC is suspended
- [ ] Synthetix synths page needs to read synth exchange fee directly from `SystemSettings.exchangeFeeRate(bytes32)`
