### ISSUE TITLE
[EPIC]: SIP-135 Shorts on L2 plus repay and liquidate with collateral

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/issues#168]
### Summary
We want to use the same collateral manager for both L1 and L2 shorts, this requires a refactor to fit the gas-limit on L2 

- [ ] L1 shorts prod Integration tests for open / close short position. `shorts-test`

- [ ] Merge in the deploy script refactor changes into  `l2-shorts-udpated-collateralstate-internal` branch https://github.com/Synthetixio/synthetix/pull/1292

- [ ] Reduce Collateral contract size by moving settings out into MixinSystemSettings to fit into L2 deploy size on `l2-shorts-udpated-collateralstate-internal`

- [ ] SIP-135 new functionality in CollateralShorts.sol - repayWithCollateral(uint id, uint repayAmount) and  liquidateFromCollateral(address borrower, uint id)

- [x] BaseCollateralManager / CollateralManagerWithInverse refactor and update deploy script https://github.com/Synthetixio/synthetix/pull/1302/files [This one does not need to be done due to the deprecation of inverseSynths)
