### ISSUE TITLE
[TASK]: Internal ETH archive node setup

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/issues#176]
### Summary
*Internal ETH archive node setup*

### Tasks
- [x] Setup machine with ubuntu server
- [x] Sync ETH archive node
- [x] Setup nginx reverse proxy with basic auth
- [x] Setup node monitoring and dashboard
- [x] Switch CI to use archive ETH node

### QA Tasks
- [x] Put node under high load and see how it behaves
- [x] Check if it works well with contract-linker

**Comment by drptbl** [comment]
<img width="791" alt="Screenshot 2021-06-06 at 17 42 46" src="https://user-images.githubusercontent.com/8177587/120931224-efa5c000-c6f0-11eb-9630-e3f64691a647.png">
<img width="782" alt="Screenshot 2021-06-06 at 17 42 55" src="https://user-images.githubusercontent.com/8177587/120931231-f16f8380-c6f0-11eb-9964-1ec313ad99d5.png">
<img width="1589" alt="Screenshot 2021-06-06 at 17 57 45" src="https://user-images.githubusercontent.com/8177587/120931233-f2081a00-c6f0-11eb-9152-0fb471c4e04c.png">
