### ISSUE TITLE
[EPIC]: Local protocol dev setup

### ISSUE THREAD

**Issue by liamzebedee** [Synthetixio/issues#209]
## Motivation
> Ale has done a huge amount of work to automate deployments on the ovm docker image, plus we have contracts-interface which just need an npm link locally, plus we can run the graph locally. I really think it’s time to take off the training wheels here. If we keep using Kovan then we’re potentially blocked on any issues arriving on Kovan! This way the fronted devs can move at speed, and it paves the way to pick up breaking changes to the contracts / dapps much earlier. Finally, Ale has been working with two engineers who can help build out this architecture more. Potentially we could even compose the whole thing in docker so you just run everything by executing a single command

### Iteration 1: 

 - [x] Modifying packages to support local-ovm artifacts.
   - [x] [subgraph](http://github.com/Synthetixio/synthetix-subgraph/)
     - [x] mock `versions.json` for local-ovm.
   - [x] [js-monorepo](http://github.com/Synthetixio/js-monorepo)
   - [x] [kwenta](http://github.com/Synthetixio/js-monorepo)
   - [x] [staking](https://github.com/Synthetixio/staking/)
 - [x] Running a local futures keeper.
 - [x] DevEx - `npm link`-ing all of these packages together.
 - [x] DevEx - Hardhat task for populating local L2 chain with fixture data. e.g. SNX for Metamask. - see clem's script https://github.com/clementbalestrat/sUSD-printer-ovm/blob/main/index.js
 - [x] Running a local price oracle keeper, replicating the ChainLink prices.
 - [x] DevEx - displaying last deployment of the L2 contracts (potentially useful, esp. with the graph) - see `node src/status.js` in https://github.com/liamzebedee/local-snx-ovm.

After this iteration, I want to run a walkthrough session with the frontend team to test how this should improve their workflow. Some learning objectives:

 * Explain how to run an ops node, and know the difference between L1 and L2 endpoints.
 * Explain how to deploy futures contracts to L2.
 * Explain how to run a local graph node.
 * Explain how to run a local futures keeper.
 * Identify the dependencies between our repos which use contract artifacts.
 * Identify when NPM packages are linked and where using the commands below.

### Iteration 2: 

 * Simplify the config/install process https://github.com/liamzebedee/local-snx-ovm/issues/1
 * Empower the frontend team to run this setup locally, so they can locally test, verify, and submit PR's to get the graph endpoints working and write tools. 

 - [ ] Integration of Kwenta<>Local Subgraph. 
 - [ ] Integration of Staking<>Local Subgraph.
 - [ ] Test integration with Kwenta<>OVM L2 network - wallets, transactions, gas limits etc.
 - [ ] Test integration with Staking<>OVM L2 network - wallets, transactions, gas limits etc.
 - [ ] Test local subgraph sync speeds vs. the testnet sync speeds.
 - [x] Script to get default account funded with SNX and sUSD.

## Notes

**Instructions on how to run the local setup are detailed here - https://github.com/liamzebedee/local-snx-ovm**.

#### Showing the local npm symlinked packages
```
npm ls --depth=0 --link=true

# for js-monorepo
for dir in packages/*; do (cd $dir && npm ls --depth=0 --link=true); done
```

#### Fast forwarding the L2 chain
This uses the seth tool from dapptools. It could be achieved with curl too.

```
# Advance the L1 chain.
ETH_RPC_URL=http://localhost:9545 seth rpc-request "evm_increaseTime" -- -s "1000000" -i append
ETH_RPC_URL=http://localhost:9545 seth rpc-request evm_mine

# Now submit a test transaction on the L2 chain, in order to finalise.
```

#### Hardhat accounts
```
Accounts
========
Account #0: 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 (10000 ETH)
Private Key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

Account #1: 0x70997970c51812dc3a010c7d01b50e0d17dc79c8 (10000 ETH)
Private Key: 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d

Account #2: 0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc (10000 ETH)
Private Key: 0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a

Account #3: 0x90f79bf6eb2c4f870365e785982e1f101e93b906 (10000 ETH)
Private Key: 0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6

Account #4: 0x15d34aaf54267db7d7c367839aaf71a00a2c6a65 (10000 ETH)
Private Key: 0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a

Account #5: 0x9965507d1a55bcc2695c58ba16fb37d819b0a4dc (10000 ETH)
Private Key: 0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba

Account #6: 0x976ea74026e726554db657fa54763abd0c3a0aa9 (10000 ETH)
Private Key: 0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e

Account #7: 0x14dc79964da2c08b23698b3d3cc7ca32193d9955 (10000 ETH)
Private Key: 0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356

Account #8: 0x23618e81e3f5cdf7f54c3d65f7fbc0abf5b21e8f (10000 ETH)
Private Key: 0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97

Account #9: 0xa0ee7a142d267c1f36714e4a8f75612f20a79720 (10000 ETH)
Private Key: 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6

Account #10: 0xbcd4042de499d14e55001ccbb24a551f3b954096 (10000 ETH)
Private Key: 0xf214f2b2cd398c806f84e317254e0f0b801d0643303237d97a22a48e01628897
```

## Ideas.

 - [ ] Fixing node publish build to be a bit quicker and incremental.
 - [ ] Investigate how to get the frontend team to write "data view" contracts that are part of our deployment pipeline.
