### ISSUE TITLE
[EPIC]: Divert inflation to shorting rewards [SCCP-92]

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/issues#21]
### Summary
Need to fund sBTC shorting rewards with inflation schedule

### Tasks
- [x] SCCP created 
- [x] Council to vote (passed)
- [x] Divert 16k/week SNX to sBTC shorting
- [x] Modify the inflation contract targets to send inflationary rewards to the shorting reward contract

### QA Tasks
- [x] Inflation rewards should go into sETH shorting and sBTC shorting rewards contracts
