### ISSUE TITLE
[TASK]: Investigate permission issues on docker-node with npm@7

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/issues#217]
### Summary
npm@7 is having permission issues on `npm install` inside `docker-node` docker container while used on CI:
https://github.com/Synthetixio/kwenta/runs/2909709703

### Tasks
- [ ] Figure out why does it happen only on npm@7 (and not on npm@6)
- [ ] Fix the root cause
- [ ] Switch Kwenta CI to use docker-node container after issue is fixed

**Comment by drptbl** [comment]
There are some issues with conjunction of Docker, npm 7 and GitHub Actions. Waiting for support reply:
https://support.github.com/ticket/personal/0/1059368

side-notes:
- npm 7 works fine without Docker
- this is not an issue with our docker container as official node docker container is also failing after updating npm from 6 to 7

**Comment by drptbl** [comment]
<img width="999" alt="Screenshot 2021-07-13 at 01 28 46" src="https://user-images.githubusercontent.com/8177587/125368049-b14b9280-e379-11eb-94e7-547c3675d2a9.png">
