### ISSUE TITLE
[TASK]: Fix kwenta e2e tests

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/issues#218]
### Summary
It seems that kwenta e2e tests are failing for some reason. Kwenta is also using an old version of synpress.

### Tasks
- [x] Figure out why e2e tests fail
- [x] Update synpress to latest version
- [x] Fix e2e tests and make sure they're passing
