### ISSUE TITLE
Build/setup (API) monitoring for any kind of endpoints that we rely on or use (including our own)

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/issues#226]
**Tasks:**
- [ ] monitor subgraphs
- [ ] monitor our nodes
- [ ] monitor synthetix-exchange-stats (https://github.com/Synthetixio/synthetix-exchange-stats)
- [ ] monitor our websites (status code 200)
- [ ] research about more endpoints that we could monitor (David S / Clem)

Depends on #227.
