### ISSUE TITLE
[EPIC] Migrate ownership of L2 contracts to a multi-sig

### ISSUE THREAD

**Issue by i-stam** [Synthetixio/issues#23]
### Summary
The `owner.js` script that is used for migrating ownership to a multisig after a system upgrade is taylor made for Gnosis Safe. We want to modify or develop a new one for supporting the use of Gnosi Multisig which is the only multisg wallet supported initially on Optimism.
### Relevant Info
Check #1154 for background on Gnosis Multisig
Multisig repo: https://github.com/ScopeLift/ovm-og-multisigwallet
There are 2 options to approach the problem:
1.  Modify the current script (`owner.js`) to be flexible enough to handle all cases i.e. migration to EOA/Multisig, evm/ovm, Safe/Multisig.
2. Create 3 distinct scripts: 1) migrate to Gnosis Safe 2) migrate to an EOA 3)migrate to Gnosis Multisig.

### Dev Tasks
- [x]  Develop a new script or modify the existing one for migrating all the ownership of a test instance to the multisig and doing a system upgrade.
 PR: https://github.com/Synthetixio/synthetix/pull/1188
- [ ] Finish all bytecode verification pending tasks
- [ ] Review and merge new scripts
- [ ] Test the owner migration in Kovan-ovm (test + official).

### Release Tasks
- [ ] Create and setup the official multisig in mainnet-optimism
- [ ] Run the script to change ownership
