### ISSUE TITLE
Introduce some kind of templating for GitHub Actions workflow files

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/issues#230]
**Summary:**
Some parts of the workflows are the same and repeated across different FE repositories. It would be great to have some kind of a tool to update everything in one go and to avoid code duplication.

**Tasks:**
- [ ] Automated PRs on dependencies updates fixing critical vulnerabilities to update them asap
- [ ] Make sure that everything is integrated in to the pipeline (not as github application)
- [ ] Add an ability to update CI docker images inside workflows across several different repositories
