### ISSUE TITLE
Setup a simple sanity check run which would follow all hyperlinks in the dapp and fail CI if there is any browser console error thrown during the run

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/issues#231]
**Summary:**
Run through the hyperlinks and fail the job if console errors are being thrown.

**Tasks:**
- [x] Utilize synpress for this task
- [x] Integrate it with staking-v2
- [ ] Integrate it with Website
- [ ] Integrate it with Stats
