### ISSUE TITLE
[EPIC] Implement L2 bridged governance

### ISSUE THREAD

**Issue by leomassazza** [Synthetixio/issues#246]
### Summary ###
We decided to use [this CrossChainAccount technique](https://github.com/gakonst/xchain-account/blob/master/contracts/CrossChainAccount.sol) to manage our ownership on L2. This means that we can continue to use the Gnosis Safe protocol dao for governance on L2.

### Tasks ###
- [ ] _(WIP by Leo)_ Merge Leo's script that cleans up ownership scripts 
- [ ] _(WIP by Ale)_ Code the two new governance bridge contracts
- [ ] Set up an integration test that lets me do some owner action with it
- [ ] Test it on a fresh pair of instances on kovan
- [ ] Write a SIP for it
- [ ] Deploy it on mainnet/s
