### ISSUE TITLE
Replace metamask connector with custom one which allows any browser wallet to be used with dApp

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/issues#26]
### Summary
Remove the metamask connector and replace it with custom one which is supposed to allow any browser wallet.

### Tasks
- [ ] @clementbalestrat please fill this in

### QA Tasks
Connect wallet and switch to L2:
- [x] metamask on chrome
- [x] metamask on firefox
- [x] metamask on brave
- [x] brave wallet on brave (switch to L2 not working)
- [x] trezor through brave wallet on brave
- [ ] trezor through metamask on brave

.....

- [ ] Check if MetaMask works properly with dApp (connect wallet/transaction at minimum)
- [ ] Check if Frame works properly with dApp (connect wallet/transaction at minimum)
- [ ] Check if Brave wallet works properly with dApp (connect wallet/transaction at minimum)
- [ ] Check if Trezor wallet works properly with dApp (connect wallet/transaction at minimum)
- [ ] Check if Ledger wallet works properly with dApp (connect wallet/transaction at minimum)
- [ ] See what happens with multiple browser wallets in place
- [ ] Check each wallet on L1 and L2

Associated PR: https://github.com/Synthetixio/staking/pull/475
