### ISSUE TITLE
[EPIC]: Futures Alpha deployment

### ISSUE THREAD

**Issue by liamzebedee** [Synthetixio/issues#273]
### Motivation

 * E2E test the futures logic.

To derisk:

- [x] https://github.com/Synthetixio/issues/issues/260

Blockers:

- [x] Running keepers for liquidation and confirmation - https://github.com/Synthetixio/futures-keepers/pull/1
- [x] Running price oracle (ChainLink or internal)
- [x] https://github.com/Synthetixio/issues/issues/180
- [x] https://github.com/Synthetixio/issues/issues/98
- [x] https://github.com/Synthetixio/issues/issues/95
- [x] https://github.com/Synthetixio/synthetix/pull/1477
- [x] https://github.com/Synthetixio/issues/issues/300
- [x] https://github.com/Synthetixio/issues/issues/302
- [x] https://github.com/Synthetixio/synthetix/pull/1485
- [x] https://github.com/Synthetixio/issues/issues/207

Pushed back to next release:

- [ ] https://github.com/Synthetixio/issues/issues/170
- [ ] https://github.com/Synthetixio/issues/issues/141
