### ISSUE TITLE
[TASK]: Simulate owner relay 

### ISSUE THREAD

**Issue by gberg1** [Synthetixio/issues#278]
### Summary
Run a whole cicle simulation of governance-bridge (https://github.com/Synthetixio/synthetix/pull/1402)

### TODO
- [x] @leomassazza Write new accept-relay-script
- [x] @mjlescano  Modify nominate.js script to target nominateNewOwner on L2 via the relay (initiatizeRelay)
- [ ]  Add "backdoor" to have the option to regain ownership for a period of time

### Runsheet
- [ ] Prepare fresh instances
  - [ ] Deploy new fresh instance in kovan L1
  - [ ] Deploy new fresh instance in kovan-ovm L2
  - [ ] Connect instances
- [ ] Change owner on L2
  - [ ] Run nominate.js in instance to nominate OwnerRelayOnOptimism
  - [ ] Run accept-relay-owner.js in instance <================ New (at TODO list)
  - [ ] Verify that the OwnerRelayOnOptimism is the new owner
  - [ ] Manual tests on L2
- [ ] Test the relay by changing a setting
  - [ ] Use L1 multisig to relay a setting change in L2
- [ ] Change owner on L2 back, via the relay
  - [ ] Use nominate-owner.js to nominate an EAO in L2 <========== Modify (at TODO list)
  - [ ] Verify EOA is nominated in L2
  - [ ] Run owner.js on L2 to acceptOwnership in L2

**Comment by mjlescano** [comment]
👍
