### ISSUE TITLE
[EPIC]: Futures Alpha Incentivized Testnet

### ISSUE THREAD

**Issue by liamzebedee** [Synthetixio/issues#318]
### Motivation

* Test futures with a public userbase, collect feedback on dapp and contracts, observe system in production (including debt pool, funding rate mechanism, frontrunning, etc).

Objectives:

- UX and dapp feedback improvements
- Is the product being used as it was designed
- Can it be frontrunned ?
- Debt pool impact.
- Liquidation system and liquidation bot is working?
- How instantaneous funding rate affects the system?
- Tools that we would need to observe system in production?

Tasks:

 - [x] Deploy (contracts, keepers, dapp). Deployment will be from kovan-ovm-futures, and an audit will likely come later from Iosiro.
 - [x] Plan sUSD faucet. (Jeremy - Kwenta)
 - [x] Add alerts for liquidation bot
 - [x] Make sUSD non-transferrable 
 - [x] Blog post - Guide (Afif / Andrew).
 - [x] Announce in Discord.
 - [x] Collect feedback.

To derisk:

 - [x] Incentivised testnet design. What is the incentive, what does it look like? e.g. Lyra trading competition

Issues:

 - [x] Mitigate frontrunning. We need a frontrunning bot that captures arbitrage profit (stemming from the [order confirmation delays thread](https://discord.com/channels/413890591840272394/870486981866586164/875550125630570546)). 
 - [ ] Price impact formula (alternative to the frontrunning bot). Afif's price impact formula should increase the cost such that frontrunning is unprofitable. It's currently a draft SIP, though worth keeping aware of.
