### ISSUE TITLE
[EPIC]: Futures Prod

### ISSUE THREAD

**Issue by liamzebedee** [Synthetixio/issues#322]
### Motivation

 * Finalise futures design and implementation before mainnet release.

To derisk:

 - [ ] Dapp feedback from [Futures Alpha Testing](https://github.com/Synthetixio/issues/issues/318).
 - [ ] Mechanism study (funding rate, effects on debt pool) from [Futures Alpha Testing](https://github.com/Synthetixio/issues/issues/318).
 - [x] https://github.com/Synthetixio/issues/issues/170
 - [ ] Final funding rate design.
   - [ ] Integrating the feedback from #cryptecon - https://github.com/Synthetixio/issues/issues/142
   - [ ] Decide on: https://github.com/synthetixio/issues/issues/87
   - [ ] The effect of OVM's lagging `block.timestamp` on funding rate calculations. Need to investigate how this affects the funding rate arbitrage, attacks relating to opening and closing a position before an update comes through, etc.
 - [ ] Review and prioritise the items in "Enhancements / Stretch Goals" - https://github.com/Synthetixio/issues/issues/106.
 - [ ] Audit complete from Iosiro.

Tasks:

 - [x] Confirmation/liquidation keeper is integrated with our logging infra and reviewed by other CC's (currently only Liam knows how to operate it).
 - [ ] https://github.com/Synthetixio/issues/issues/141
 - [ ] https://github.com/Synthetixio/issues/issues/143
 - [ ] Remaining tests for futures logic:
   - [ ] Unit tests
     - https://github.com/Synthetixio/issues/issues/106
     - https://github.com/synthetixio/issues/issues/88
     - implement scaffolded tests - https://github.com/synthetixio/issues/issues/103
   - [ ] Integration tests - https://github.com/Synthetixio/issues/issues/159
 - [ ] Merge into `develop`.
    - [ ] Fix the test suite to work with L2 futures deployment (CI has been red forever on `futures-implementation`).
 - [ ] Derisk our [bus factor](https://en.wikipedia.org/wiki/Bus_factor). We need to get some folks on the Western team to understand the architecture of the futures system, so that if we're asleep or we die, someone else can put out fires.
