### ISSUE TITLE
[EPIC] Extend balancer exchange for new stock synths

### ISSUE THREAD

**Issue by gberg1** [Synthetixio/issues#33]
### Summary

New stock synths are being added to Kwenta. Make sure we support after hours trading by extending current balancer pools.

### Tasks
- [x] Look into David's previous PR for balancer pools
- [ ]  sFB
- [ ] sMSFT
- [ ] sGOOG
- [ ] sNFLX
- [ ] sAMZN
- [ ] sAAPL
- [ ] sCOIN (get address for sCOIN when ready)

### QA Tasks
- [ ] Add first QA step here
