### ISSUE TITLE
[EPIC] Use `estimateGas` on L2 Kwenta and removed hardcoded gas limit

### ISSUE THREAD

**Issue by JChiaramonte7** [Synthetixio/issues#42]
### Summary
Currently the gas limit is hardcoded for L2. This is no longer an optimal solution. We must switch back to using `estimateGas`

### Tasks
- [x] Remove conditionals for hardcoded gas limit on L2.

### QA
- [ ] Make sure gas limit is no longer 8999999 during metamask TX
- [ ] Make sure TX goes through

**Comment by kelonye** [comment]
Looking good. Have validated the PR as well 👍🏽
