### ISSUE TITLE
[DESIGN] Kwenta exchange design improvements

### ISSUE THREAD

**Issue by gberg1** [Synthetixio/issues#47]
### Summary
Scope out and implement the following design changes to kwenta:

  - Singular Chart with option to Toggle Dual Chart (will require design work)
  - Figure out better submit trade button placement
  - Add trade entry points to chart on kwenta
  - Contrast/readability review
  - Individual profit and losses for positions on dashboard

### Tasks
- [ ] Add first actionable task here

### QA Tasks
- [ ] Add first QA step here

**Comment by erikatruscott-ux** [comment]
- [x] Singular Chart with the option to Toggle Dual Chart 
- [x] Figure out better submit trade button placement
- [x] Add trade entry points to chart on kwenta
- [x] Contrast review
- [x] Individual profit and losses for positions on dashboard
- [x] Market hours for stocks

**Singular chart option to toggle dual.**
![image](https://user-images.githubusercontent.com/80739958/117340043-bdf6ca80-aea0-11eb-9a42-c772b7d76dee.png)

Prototype here:
https://www.figma.com/proto/sghReDviy1lcr6kkNqlc0e/Kwenta-User-Flows?page-id=0%3A1&node-id=3073%3A0&viewport=657%2C-6056%2C0.2915821373462677&scaling=min-zoom
Design here:
https://www.figma.com/file/sghReDviy1lcr6kkNqlc0e/Kwenta-User-Flows?node-id=3073%3A0

Colour contrast - accessibility review
Updating 'Blueberry' to be a tad lighter brings the contrast into a healthier range.
I've also explored an even lighter Blueberry, lets keep an eye on it, and make it even lighter if users are still struggling.
![image](https://user-images.githubusercontent.com/80739958/117339763-68222280-aea0-11eb-9401-cf33cbc468ba.png)

**Comment by Andotlas** [comment]
For the market hours for stocks: 

We need a timer that indicates how long a user has to trade a given stock on Kwenta before the market closes and, conversely, how long they have to wait until a given market is reopened. I suggest we add a section in the box of metrics below charts (in the exchange tab) which includes a timer for market hours. 

A bonus visual would be to show on a stock's chart when the market open/closes with a different color or linebreak to better indicate market hours.

**Comment by erikatruscott-ux** [comment]
I've updated the proto with the above suggestions..
See what you think?
https://www.figma.com/proto/sghReDviy1lcr6kkNqlc0e/Kwenta-User-Flows?page-id=0%3A1&node-id=3073%3A0&viewport=1096%2C-10813%2C0.5&scaling=scale-down

When the market is open
![image](https://user-images.githubusercontent.com/80739958/117340203-ef6f9600-aea0-11eb-935b-e1fb4cd69d01.png)

When the market is closed:
![image](https://user-images.githubusercontent.com/80739958/117340246-fbf3ee80-aea0-11eb-91d8-0724301ab917.png)

**Comment by erikatruscott-ux** [comment]
@Andrew-Synthetix 

Herewith the individual profits and losses for assets.
I have also thought it might be nice to show overall totals (and a visualisation) in the top panel...if this is doable ofcourse...

![image](https://user-images.githubusercontent.com/80739958/117418928-46668100-af1c-11eb-8e14-297536e81e7d.png)
