### ISSUE TITLE
[TASK] Create e2e tests for shorting on Kwenta

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/issues#57]
### Summary
Create e2e tests for shorting on Kwenta

### Tasks
- [ ] Create page objects for associated pages
- [ ] Create tests for shorting on Kwenta

### QA Tasks
- [ ] Tests shouldn't be flaky and pass every time on CI when run in parallel
