### ISSUE TITLE
Create test instances for Kwenta and Staking using Bison Trails as ethereum node provider

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/issues#59]
### Summary
Create test instances for Kwenta and Staking using Bison Trails as ethereum node provider instead of Infura.

### Tasks
- [x] Create test instance for Kwenta
- [ ] Create test instance for Staking

### QA Tasks
- [x] Verify if everything is working properly on Kwenta
- [ ] Verify if everything is working properly on Staking
- [ ] Performance testing on Biston Trails

**Comment by drptbl** [comment]
Kwenta:
https://github.com/Synthetixio/kwenta/commits/bison-trails
https://kwenta-git-bison-trails-synthetixio.vercel.app/

**Comment by drptbl** [comment]
new task: https://github.com/Synthetixio/issues/issues/127
