### ISSUE TITLE
[EPIC]: Set up Synthetix Ambassadors tooling

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/issues#6]
### Summary
Design and build the delegation UI to enable the Synthetix Ambassadors to be delegated to.

### Examples

https://yuni.finance/

### Tasks
- [x] Design the delegation interface
- [x] Implement the front-end
- [ ] Create a cron-job for the Synthetix Ambassadors to pay for the gas for delegators who do not want to pay for delegation tx ```delegateBySig```
- [x] Ambassadors need a space to receive input and signals from those delegating to them (signalling to add/remove protocols, how to vote on different proposals)

### QA Tasks
- [x] A user should be able to delegate to the Synthetix Ambassador multi-sig (either by paying for their own tx cost or signing a tx that will be executed later by the Ambassadors.
- [x] A user should be able to delegate different protocols to the Synthetix Ambassadors
- [x] A user should be able to signal to the Ambassadors to add support for different protocols
