### ISSUE TITLE
Investigate DNS caching issue on Staking

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/issues#60]
### Summary
Investigate DNS caching issue on Staking

### Tasks
- [x] Investigate DNS caching issue on Staking
- [x] Possibly fix/improve it

### QA Tasks
- [x] Make sure it works

**Comment by drptbl** [comment]
Partially fixed.
