### ISSUE TITLE
Vercel deployments should be done through CI, not GitHub integration

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/issues#61]
### Summary
Vercel deployments should be done through CI, not GitHub integration. Mainly because:
- we control deployment based on CI statuses
- we control the build system and build dependencies

### Tasks
- [ ] Deploy Kwenta through Vercel CLI on CI instead of GitHub integration
- [ ] Deploy Staking through Vercel CLI on CI instead of GitHub integration
- [ ] Deploy Website through Vercel CLI on CI instead of GitHub integration

### QA Tasks
- [ ] Make sure deployments work

**Comment by drptbl** [comment]
Will be finished after Matomo setup is done.
https://github.com/Synthetixio/issues/issues/299
https://github.com/Synthetixio/issues/issues/305
