### ISSUE TITLE
[TASK] Switch to etherscan API for fetching transactions in e2e tests

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/issues#62]
### Summary
Currently we fetch transactions directly from etherscan in e2e tests (https://kovan.etherscan.io/tx/0x...) which sometimes throws bot protection up from cloudflare (recaptcha) thus breaking the tests.

https://github.com/Synthetixio/kwenta/runs/2415106330
<img width="1389" alt="Screenshot 2021-04-23 at 14 42 47" src="https://user-images.githubusercontent.com/8177587/115872795-815bb580-a442-11eb-8c14-93c7f1b1a7bb.png">
<img width="1028" alt="Screenshot 2021-04-23 at 14 42 56" src="https://user-images.githubusercontent.com/8177587/115872767-786ae400-a442-11eb-88e2-8c2930a361bf.png">

### Tasks
- [x] Make etherscan API easily accessible from e2e tests (synpress integration)
- [x] Utilize Etherscan API directly to fetch transactions and avoid bot protection in Kwenta e2e tests

### QA Tasks
- [x] Make sure transaction data fetching works properly in e2e tests

**Comment by drptbl** [comment]
https://dashboard.cypress.io/projects/camtjp/runs/329/test-results/43af573f-0fe5-43d9-92d9-19abfbd1de10
