### ISSUE TITLE
[EPIC]: Implement futures contracts

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/issues#7]
### Summary

Although the structure of the futures contracts has already been thoroughly specified in [SIP-80](https://sips.synthetix.io/sips/sip-80), the implementation is only partially complete. The contract implementation strategy will proceed as follows:

1. ~~Review and validate existing logic~~ (done)
2. Complete basic functionality
3. Refactor to deploy on L2
4. Add enhanced features

### Tasks

See the [Futures project board](https://github.com/orgs/Synthetixio/projects/7).

#### Progress

I'm including the story points for each task along side it in parentheses. The overall story points for each heading
is the sum of the story points of the tasks or headings underneath it. To track progress, at the end of each Friday
I will record here the overall number of points completed so far on non-enhancement story points.

| Date | Points |
| ---- | ------- |
| 2021-4-16 | (11/65) |
| 2021-4-23 | (15/65) |
| 2021-4-30 | (19/65) |

#### Prep (2/2)

- [x] Review and clean up [SIP-80](https://sips.synthetix.io/sips/sip-80) ([PR](https://github.com/Synthetixio/SIPs/pull/450)) (1)
- [x] Review existing code (1)

#### Basics (13/30)

- [x] Basic oracle feeds (1)
- [x] Market settings (1)
- [x] Opening positions (1)
- [x] Order cancellation (1)
- [x] Exchange fees (1)
- [x] Margin top-ups and withdrawals (1)
- [x] Modifying positions (fee / submission / changing / closing) (2)
- [x] Next-price order fulfillment (1)
- [x] Leverage, PnL, and remaining margin (1)
- [ ] Market views (0.5)
- [ ] Position views (0.5)
- [x] Liquidation price calculations (1)
- [ ] Basic liquidations (2)
- [ ] Funding (3)
- [ ] Max market size constraints (1)
- [x] Aggregated market debt (2)
- [ ] Confirmation keeper (2)
- [ ] Liquidation keeper (2)
- [ ] Market management (3)
- [ ] Add a static exchange fee in case we need to combat front-running (also modify the SIP) (3)

#### (Infra)Structure (2/18 + ????)

It's unknown to me at this stage how long the OVM refactor will take, but it seems like it's worth at least 5 points,
probably closer to 10.

- [x] Proxy (1)
- [x] Convert to signed decimal math logic (1)
- [ ] Cross-market debt snapshot aggregation (2)
- [ ] Funding / profits paid to pool instead of burning debt (3)
- [ ] Additional (simplified) position closing function (1)
- [ ] External market settings contract (1)
- [ ] Position modification must be sensitive to settlement / fee reclamation (2)
- [ ] OVM/V3 refactor (????)
- [ ] Market deployment / management scripts + testing (3)
- [ ] Contract interfaces (1)
- [ ] External documentation (2)
- [ ] Inline documentation (1)

#### Enhancements (0/27)

- [ ] Batched order confirmation / liquidation for keeper efficiency and responsiveness (2)
- [ ] Gas optimisation (2)
- [ ] Pausable from SystemStatus contract (no funding rate and orders can close but not open) (2)
- [ ] Price divergence circuit breaker + keeper (relies on pause functionality) (1)
- [ ] Funding max slew rate (2)
- [ ] Gas Tank (5)
- [ ] Separated state (1)
- [ ] Historical price / restrospective liquidations (4)
- [ ] Fill orders with prices of the roundId immediately after they submitted rather than the current price, in case confirmation keepers fail to fill the order in time. (2)
- [ ] Tokenise positions to support multiple orders per account (4)
- [ ] Report overall market leverage and leverage per-side (2)

#### Unit Testing

- [ ] Ensure 100% coverage (1)

##### Futures Market (1/5)

- [ ] Public variables
- [x] marketSizes
- [ ] marketDebt
- [x] proportionalSkew
- [ ] currentFundingRate
- [ ] unrecordedFunding
- [ ] netFundingPerUnit
- [ ] fundingSequenceLength
- [ ] notionalValue
- [x] profitLoss
- [ ] accruedFunding
- [ ] remainingMargin
- [x] liquidationPrice
- [ ] canLiquidate
- [x] currentLeverage
- [x] orderFee
- [ ] canConfirmOrder
- [x] Parameter setters
- [x] cancelOrder
- [ ] submitOrder
- [ ] closePosition
- [ ] confirmOrder
- [ ] liquidatePosition

##### Futures Market Manager (0/2)

- [ ] marketForAsset
- [ ] markets
- [ ] numMarkets
- [ ] allMarkets
- [ ] marketsForAssets
- [ ] totalDebt
- [ ] addMarkets
- [ ] removeMarkets
- [ ] removeMarketsByAsset
- [ ] issueSUSD
- [ ] burnSUSD

##### Futures Market Data (0/2)

- [ ] marketSummaries
- [ ] marketSummariesForAssets
- [ ] allMarketSummaries
- [ ] marketDetails
- [ ] marketDetailsForAsset
- [ ] positionDetails
- [ ] positionDetailsForAsset

#### Integration / Scenario Testing (0/3)

- [ ] TODO

**Comment by andytcf** [comment]
recreated on #106
