### ISSUE TITLE
[EPIC]: GrantsDAO V2

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/issues#8]
### Summary
Implement grantsDAO workflow that includes a frontend that interacts with a smart contract handling the proposal and triage of proposals and request for the Synthetix grants DAO

### Tasks
- [ ] Design the frontend that houses the proposals
- [ ] Implement the grantsDAO frontend
- [ ] Relaunch grantsDAO v2 contract
- [ ] Set up grantsDAO multisig
- [ ] Set up grantsDAO snapshot space
- [ ] Integrate Safesnap bridging the snapshot space to the grantsDAO multisig (allowing for gas-less voting to trigger on-chain execution) 

### QA Tasks
- [ ] A user should be able to create a proposal on the frontend and confirm it on the contract
- [ ] gDAO members are able to successfully use the gDAO multisig to approve, reject and progress proposals
- [ ] A successful proposal on snapshot should trigger an on-chain call
