### ISSUE TITLE
[TASK] Futures Final Checklist

### ISSUE THREAD

**Issue by zyzek** [Synthetixio/issues#85]
Story Points: 3

We need to ensure that a user can interrogate all the important pieces of information about the market and their positions.

- [ ] Compare this against the user stories and designs and add any missing functions.

The following functions must exist:

- [ ] Margin Modification
- [ ] Margin Withdrawal
- [ ] Order Submission
- [ ] Order Cancellation
- [ ] Close Position

The following views must exist and possess accompanying tests:

- Market
    - [x] base asset
    - [x] total size and side sizes
    - [ ] debt
    - [ ] skew
    - [ ] funding rate & time last recomputed
    - [ ] unrecorded funding
    - [ ] funding sequence & length
    - [ ] net funding per base unit
    - [ ] Current round Id
    - [ ] asset price
    - [ ] Market parameters
        - [ ] exchange fee
        - [ ] max leverage
        - [ ] max market debt
        - [ ] minimum initial margin
        - [ ] max funding rate
        - [ ] max funding rate skew
        - [ ] max funding rate delta
    - [ ] liquidation fee (maybe this doesn't need to be in the market itself if it is a global?)
- Order
    - [ ] size
    - [ ] leverage
    - [ ] fee
    - [ ] roundId
    - [ ] pending status
    - [ ] whether the order can be confirmed
    - [ ] fee for a potential order
    - [ ] max order size
- Position
    - [ ] initial margin
    - [ ] size
    - [ ] fill price & funding index
    - [ ] remaining margin
    - [ ] notional value
    - [ ] profit and loss
    - [ ] accrued funding
    - [ ] liquidation price
    - [ ] whether the position can be liquidated
    - [ ] current leverage
    - [ ] Withdrawable margin

- [ ] Ensure these are reflected in the `FuturesMarketData` contract.

**Comment by zyzek** [comment]
Merged into #106
