### ISSUE TITLE
Allow any browser wallets to connect to dApps

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/issues#9]
### Summary
Create a new library wrapping/extending the onboard.js by blocknative that gives us more flexibility to support other wallets such as frame.sh and not just browser wallets. 

### Tasks
- [x] Do R&D on how to support ledger and trezor native integrations without going through browser wallets
- [x] Create a browser wallet option that wraps frame.sh and metamask

### QA Tasks
- [ ] Make sure it works on Kwenta
- [x] Make sure it works on Staking

**Comment by andytcf** [comment]
@drptbl this one is waiting on you to QA, it focusses on allowing any browser wallets to connect via the onboard, the coinbase compatibility will come later

**Comment by drptbl** [comment]
@andytcf frame.sh works but you can't add optimism mainnet to it anyway (wallet issue, not our dapp).

**Comment by drptbl** [comment]
Staking part is done.

**Comment by andytcf** [comment]
@clementbalestrat still needs to be added to kwenta
